## My First Notebook

In [6]:
import pandas as pd

In [7]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\sharon\appdata\local\programs\python\python310\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\Sharon\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [ ]:
import pandas as pd

In [9]:
# to read just one sheet to dataframe:
df = pd.read_excel("C:/Users/Sharon/Desktop/jupyter notebook/114A101.xls", sheet_name="標單詳細表")

In [10]:
df

,新竹市政府,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,詳細價目表[標單],NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,工程名稱,新竹市北區延平地下停車場(含北新公園)興建工程,NaN,NaN,會計科目,NaN,NaN
...,...,...,...,...,...,...,...
2172,壹.十,營業稅(5%),式,1,NaN,0,NaN
2173,NaN,合計(壹),NaN,NaN,NaN,NaN,NaN
2174,NaN,總價(總計),NaN,NaN,NaN,NaN,NaN
2175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2176,...,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.columns

Index(['新竹市政府', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [12]:
df.iloc[:,1]

0                           NaN
1                           NaN
2                           NaN
3                           NaN
4       新竹市北區延平地下停車場(含北新公園)興建工程
                 ...
2172                    營業稅(5%)
2173                      合計(壹)
2174                     總價(總計)
2175                        NaN
2176                        NaN
Name: Unnamed: 1, Length: 2177, dtype: object

In [ ]:
#篩選資料中含有適用焚化再生粒料工程的關鍵字
df_brick = df[df.iloc[:,1].str.contains('磚',na=False)]
df_CLSM=df[df.iloc[:,1].str.contains('控制性低強度回填材料',na=False)]
df_stone=df[df.iloc[:,1].str.contains('緣石',na=False)]
df_AC=df[df.iloc[:,1].str.contains('瀝青混凝土',na=False)]
df_graded=df[df.iloc[:,1].str.contains('級配',na=False)]

In [14]:
df_AC

Empty DataFrame
Columns: [新竹市政府, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6]
Index: []

In [15]:
print("磚:",df_brick.iloc[:,3].sum(),"CLSM:",df_CLSM.iloc[:,3].sum(),"緣石:",df_stone.iloc[:,3].sum(),"瀝青混凝土:",df_AC.iloc[:,3].sum(),"級配:",df_graded.iloc[:,3].sum())

磚: 9308 CLSM: 0 緣石: 902 瀝青混凝土: 0 級配: 0

In [16]:
filter_df = df[(df.iloc[:,1].str.contains('控制性低強度回填材料')) | (df.iloc[:,1].str.contains('磚'))| (df.iloc[:,1].str.contains('緣石'))|(df.iloc[:,1].str.contains('瀝青混凝土'))|(df.iloc[:,1].str.contains('級配'))|(df.iloc[:,1].str.contains('水泥'))|(df.iloc[:,1].str.contains('級配'))]

filter_df

,新竹市政府,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
39,壹.一.2.13,1:2水泥砂漿(排樁用),m3,2895,NaN,0,"0406100003201,#"
67,壹.一.3.14,無收縮水泥,柱,72,NaN,0,"0230005568,#"
75,壹.一.4.4,F2 1:3水泥砂漿+磨石子地磚60x60cm(透心,M2,241,NaN,0,"040610000254,#,"
77,壹.一.4.5,F3 1:3水泥砂漿+仿石質止滑樓梯磚,M2,141,NaN,0,"040610000205,#"
80,壹.一.4.7,F5 地坪貼仿石質石英磚30x60cm,㎡,59,NaN,0,"0406100554,#,"
83,壹.一.4.10,"地坪警示帶(磨石子透心地磚,止滑面)",㎡,6,NaN,0,"0406100557,#,"
85,壹.一.4.12,牆面1:3水泥砂漿+防霉乳膠漆+警示漆H=,M2,1608,NaN,0,"040610000206,#,"
89,壹.一.4.14,牆面1:3水泥砂漿+防霉乳膠漆,M2,468,NaN,0,"04061000027,#,"
91,壹.一.4.16,W4 牆面貼仿石質石英磚30x30cm,㎡,186,NaN,0,"0406100563,#,"
92,壹.一.4.17,W5 牆面1:3水泥砂漿粉光,M2,689,NaN,0,"040610000271,#,"
93,壹.一.4.18,W6 牆面貼仿石質石英磚30x30cm,㎡,522,NaN,0,"0406100565,#,"
94,壹.一.4.19,W6 輕隔間牆貼仿石質石英磚30x30cm,㎡,733,NaN,0,"0406100566,#,"
111,壹.一.4.36,"地下室頂板防水層(覆土區,面磚區)",㎡,3675,NaN,0,"0290000744,#"
1034,壹.二.2.5.1.3,產品，防火磚(200mmx130mmx50mm/塊),塊,10,NaN,0,"M71900022819,澤"
1987,壹.三.1.1.1,人行道鋪設透水磚 th=6cm,M2,1519,NaN,0,"0934100550,#"
1988,壹.三.1.1.2,步道鋪設透水磚 th=6cm,M2,671,NaN,0,"0934100560,#"
1989,壹.三.1.1.3,草坪周邊廣場鋪設透水磚 th=6cm,M2,676,NaN,0,"0934100562,#"
1990,壹.三.1.1.4,0.9*1.8m共享單車格鋪設透水磚 th=6cm,M2,59,NaN,0,"0934100564,#"
1991,壹.三.1.1.5,機車道鋪設透水磚 th=8cm,M2,103,NaN,0,"0934100566,#"
1992,壹.三.1.1.6,1*2m機車格鋪設透水磚 th=8cm,M2,94,NaN,0,"0934100568,#"
1995,壹.三.1.1.9,隔線用-仿石線型透水磚(自然混色面)施作,M,264,NaN,0,"0321000555,#"
1999,壹.三.1.1.11,高壓緣石(洗石子面-邊界用)施作 th=,M,418,NaN,0,"09780000012,#"
2001,壹.三.1.1.12,高壓緣石(洗石子面-單側道路用)施作 th=,M,484,NaN,0,"097800000112,#"
2006,壹.三.1.1.16,無障礙高壓導盲磚(警示點狀/條狀)鋪設,M2,20,NaN,0,"0321000588,#"
2047,壹.三.2.1.1.1,一樓室內(綠建材)磨石子透心石面磚,M2,71,NaN,0,"0290000696,#"
2050,NaN,磚 (止滑溝刷面灰色)60*30*2cm,NaN,NaN,NaN,0,NaN
2052,壹.三.2.1.2.1,室內(綠建材)磨石子透心石面磚,M2,110,NaN,0,"0290000704,#"
2054,壹.三.2.1.2.2,室內(綠建材)無障礙磨石子透心石面磚,M2,21,NaN,0,"0290000698,#"
2057,壹.三.2.1.3.1,室內(綠建材)磨石子透心石面磚,M2,114,NaN,0,"0290000705,#"
2059,壹.三.2.1.3.2,室內(綠建材)無障礙磨石子透心石面磚,M2,13,NaN,0,"0290000698,#"